version: '3.4'

services:
  quizmaster.telegrambot:
    image: ${DOCKER_REGISTRY-}quizmastertelegrambot
    build:
      context: .
      dockerfile: src/QuizMaster.TelegramBot/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=umidjon
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=quizmasterdb
    depends_on:
      - quizmaster.database

  quizmaster.database:
    image: postgres:latest
    container_name: quizmaster.database
    environment:
      - POSTGRES_DB=quizmasterdb
      - POSTGRES_USER=umidjon
      - POSTGRES_PASSWORD=root
    volumes:
      - db-data:/var/lib/postgresql/data  
    ports:
      - 5432:5432

volumes:
  db-data:


